### PR TITLE
Add a health check for Puppetboard

### PR DESCRIPTION
**Pull request by vladgh**
Includes installing `curl` package and tests

### CODE REVIEW

**Comment by garethr** [comment]
@vladgh thanks for this, good idea. A couple of issues:

1. The `COPY Dockerfile /` instruction should always be at the end, otherwise there is a risk of it being cached and not showing the actual Dockerfile used to build the image. If you could move the healthcheck over that please.

2. The tests fail in Travis, and when I run them locally. I'm not sure why exactly but they hang on the new check for the curl package. Do you see these running cleaning locally?

**Comment by garethr** [comment]
Ah, for `2` I think I see what's happening. Puppetboard only starts when PuppetDB is running, and so the healthcheck fails - ie. the container gets stuck in starting. Which means that the serverspec tests wait for all the timeouts, which amount to 15 minutes.

Locally the tests do eventually pass:

```
Finished in 15 minutes 40 seconds (files took 1.73 seconds to load)
```

On Travis this is too long and they timeout.

I think the approach here should probably be to disable the healthcheck for the tests. Docker run can take the `--no-healthcheck` argument. We just need to work out how to pass that though ServerSpec.

**Comment by vladgh** [comment]
I made the requested change to the Dockerfile instruction.

Unfortunately, there is no 'NoHealthCheck' or similar in the latest API https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate which can be passed as an option to the docker-api gem. As far as I see, at least. So I created a new context for the spec tests, which overrides the CMD with an infinite loop. We don't really need to actually start `gunicorn` because none of the test relate to that. They just look for installed packages and files.

Another thing I don't really get is why Hound recommends double quotes for strings. Is that a new best practice?

**Comment by garethr** [comment]
@vladgh good solution. One quick request. If you could change the name of the shared context so the overriding of the `CMD` is more explicit in the tests. We already have a shared context for `with a docker container` which is the same except for this. Maybe change to `with a docker container with a dummy cmd`?

Hound should be using the same rubocop config file as that run in Travis. I've just killed the integration for the moment.

**Comment by vladgh** [comment]
Of course. I've changed it.

**Comment by vladgh** [comment]
The build fails due to an unrelated bug:

```
Rakefile:164:3: C: Use 2 (not 4) spaces for indentation.
      sh "docker pull #{image}"
  ^^^^
```

Do you want me to fix it here?

**Comment by garethr** [comment]
@vladgh thanks, I'd fixed that in master so just merged and everything passed. This will be in the images next time we release the set. Much appreciated.

**Pull request merged**
