### PR TITLE
Refs #4: Configurable autosign setting

### PR DESCRIPTION
**Pull request by tscholz**
Hi,

I'm also support the idea of having a configurable autosign setting as discussed in issue #4. So I took the code proposed by @vladgh and put it into the entry-point file.

Thanks for looking into this!

### CODE REVIEW

**Comment by underscorgan** [comment]
Hi @tscholz, thanks for the PR!

I think I prefer this implementation to the implementation in #65 since it gives you the flexibility of loading from a mounted autosign.conf, but isn't backwards incompatible with the current setups. 

I think it's valuable to have autosign enabled by default for ease of initial experimentation, but definitely understand the need to have it disabled (or at least limited with autosign.conf)

**Comment by underscorgan** [comment]
@stahnma since you were involved in the conversation on #4, want to take a look here / #65 ?

**Comment by underscorgan** [comment]
(ticket migrated to https://tickets.puppetlabs.com/browse/CPR-578)

**Comment by kratan** [comment]
Hi,
what's best practice to put file autosign.sh in an docker environment?

**Comment by underscorgan** [comment]
Hi @kratan, you'll want to bind mount that file into the running container, so assuming we're working off of this PR something like
```
AUTOSIGN=/usr/local/bin/autosign.sh docker run --mount type=bind,source="$PWD/autosign.sh",target=/usr/local/bin/autosign.sh puppet/puppetserver-standalone
```
or, with the old `--volume` syntax
```
AUTOSIGN=/usr/local/bin/autosign.sh docker run -v ~/autosign.sh:/usr/local/bin/autosign.sh puppet/puppetserver-standalone
```

More docs on that are available [here](https://docs.docker.com/storage/bind-mounts/)

**Comment by tscholz** [comment]
Hi,

thank you for reviewing this. Is there anything that I can do to help getting this merged soon?

**Comment by underscorgan** [comment]
I'll get the puppetserver and puppetserver-standalone images rebuilt and published this afternoon

**Comment by underscorgan** [comment]
Images with this change have been published!

**Comment by tscholz** [comment]
Thank you very much! 👍

**Pull request merged**
